name: Build and Release cloudflared

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build cloudflared for Linux and Windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22.x]
        os:
          - linux
          - windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up build output dir
        run: mkdir -p dist

      - name: Build cloudflared
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
            GOOS=windows GOARCH=amd64 go build -o dist/cloudflared-windows-amd64.exe ./cmd/cloudflared
          else
            GOOS=linux GOARCH=amd64 go build -o dist/cloudflared-linux-amd64 ./cmd/cloudflared
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudflared-${{ matrix.os }}-amd64
          path: |
            dist/cloudflared-*
  release:
    name: Release cloudflared binaries
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List build outputs
        run: ls -lh dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/cloudflared-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 